# *********************************************************************
# *************           IBERIA L.A.E.                   *************
# *************       by Software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a deployment in a development environment with github workflow
# This action'll need a runner to compile and process data for its use.
#
# currently it is only possible to configure 
# two types of languages "java and angular"

name: Develop
description: 'Deployment to develop'

runs:
  using: "composite"
  steps:
    # Nota: 
    # Remplace action's with custom shell script to future
    # for segurity - location in (../utils/)
    # Step 1 
    - name: checkout
      uses: actions/checkout@v2
    # Step 2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    # Step 3
    - name: Building Artifact
      shell: bash
      env:
        SCRIPT: ${{ github.workspace }}/.github/action/utils/
        # angular or java
        LANGUAGE: 
      run: |
      ${{ env.SCRIPT }}/build-maven.sh ${{ github.workspace }} ${{ env.LANGUAGE }} 
    # Step 4
    - name: Registy Artifact
      shell: bash
      env:
        SCRIPT: ${{ github.workspace }}/.github/action/utils/
        REPOSITORY_URL: "https://nexus.corp.iberia.es"
        RELEASE: false
      run: |
      # path in script repository nexus is /repository/snapshots/ and /repository/releases/
      ${{ env.SCRIPT }}/nexus-registry.sh ${{ env.REPOSITORY_URL }} ${{ env.RELEASE }}
  steps:
    # implement sonar
    # Step 1
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    # Step 2
    - name: Scan
      shell: bash
      env:
          SCRIPT: ${{ github.workspace }}/.github/action/utils
          SONAR_URL:
          SONAR_USER:
          SONAR_PASS:
          # angular or java
          SONAR_LANGUAGE:
      run: |
        ${{ env.SCRIPT }}/sonar-scanner.sh ${{ env.SONAR_URL }} ${{ env.SONAR_USER }} ${{ env.SONAR_PASS }} ${{ env.SONAR_LANGUAGE }} ${{ github.workspace }}
  steps:
    # instance software.
    # Step 1
    - name: Deploy
    # Step 2
    - name: Health Check
