# *********************************************************************
# *************           IBERIA L.A.E.                   *************
# *************       by Software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a deployment in a development environment with github workflow
# This action'll need a runner to compile and process data for its use.

name: Develop
description: 'Deployment to develop'

runs:
  using: "composite"
  steps:
    # Nota: 
    # Remplace action's with custom shell script to future
    # for segurity - location in (../utils/)
    # Step 1 
    - name: checkout
      uses: actions/checkout@v2
    # Step 2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    # Step 3
    - name: Building Artifact
      shell: bash
      env:
        SETTINGS: ${{ github.workspace }}/.github/cicd/setting.xml
      run: |
        echo "***************************************************"
        echo "Building..."
        echo "***************************************************"
        # mvn clean install -s ${{ env.SETTINGS }} -Ddocker.customTag=ci-${{ github.run_id }} --batch-mode  //no operative code - remove
        mvn -B package --file ${{ github.workspace }}/pom.xml    #pom.xml maven compile, it's need present in root repository.
  steps:
    - name: Scan
    # implement sonar
  steps:
    - name: Registy
    # Implement nexus
  steps:
    - name: Deploy
    # instance software.
  steps:
    - name: Health Check
