# *********************************************************************
# *************           IBERIA L.A.E.                   *************
# *************       by Software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a deployment in a development environment with github workflow
# This action'll need a runner to compile and process data for its use.
#
# currently it is only possible to configure 
# two types of languages "java and angular"

name: Develop
description: 'Deployment to develop'

runs:
  using: "composite"
  steps:
    # Nota: 
    # Remplace action's with custom shell script to future
    # for segurity - location in (../utils/)
    env:
      SCRIPT: ${{ github.workspace }}/.github/action/utils/
      LANGUAGE:
    # Step 1 
    - name: checkout
      uses: actions/checkout@v2
    # Step 2 - Reemplace with install process jdk and configure path environment
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    # Step 3   - Reemplace with install process node.js
    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    # Step 4
    - name: Building Artifact
      shell: bash
      run: |
      ${{ env.SCRIPT }}/build-maven.sh ${{ github.workspace }} ${{ env.LANGUAGE }}
  steps:
    # implement sonar
    env:
      SCRIPT: ${{ github.workspace }}/.github/action/utils/
      LANGUAGE:
    # Step 1
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    # Step 2
    - name: Scan
      shell: bash
      env:
          SONAR_URL:
          SONAR_USER:
          SONAR_PASS:
      run: |
        ${{ env.SCRIPT }}/sonar-scanner.sh ${{ env.SONAR_URL }} ${{ env.SONAR_USER }} ${{ env.SONAR_PASS }} ${{ env.LANGUAGE }} ${{ github.workspace }} ${{ github.ref }}
  steps:
     # deploy artifact to registry repository
     env:
        SCRIPT: ${{ github.workspace }}/.github/action/utils/
        LANGUAGE:
    - name: Registy Artifact
      shell: bash
      env:
        REPOSITORY_URL:
      run: |
      # path in script repository nexus is /repository/snapshots/ and /repository/releases/
      ${{ env.SCRIPT }}/nexus-registry.sh ${{ env.REPOSITORY_URL }} ${{ env.LANGUAGE }} ${{ github.ref }}
  steps:
    # instance software.
    # Step 1
    - name: Deploy
    # Step 2
    - name: Health Check
