# *********************************************************************
# *************           IBERIA L.A.E.                   *************
# *************       by software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a publish software with github workflow
# This action'll need a runner to compile and process data for its use.

name: Release
description: 'publish software'

runs:
  using: "composite"
  steps:
    - name: control version
    # control version pom, if version existe publish then reject deploy.
  steps:      
    - name: Building Artifact
      shell: bash
      env:
        SETTINGS: ${{ github.workspace }}/.github/cicd/setting.xml
      run: |
        echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
        echo "Building..."
        echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
        mvn clean install -s ${{ env.SETTINGS }} -Ddocker.customTag=ci-${{ github.run_id }} --batch-mode
  steps:
    - name: Unit test
    # Implement sonar quebe
  steps:
    - name: vulnerability software
    # Implement veracode
  steps:
    - name: registy software
    # Implement nexus
  steps:
    - name: build image
    # create AMI/docker image with terrafom and ansible 
  steps:
    - name: Deploy
    # instance image with terrafom plan
  steps:
    - name: Health Check
    # test system up
  steps:
    - name: Integration test
     # test requesto to contract api ( if existe definition test then runner test )
  steps:
    - name: Tagging
    # create tag with version pom. control
