# *********************************************************************
# *************           IBERIA L.A.E.                   *************
# *************       by Software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a deployment in environment with github workflow
# This action'll need a runner to compile and process data for its use.
#
# currently it is only possible to configure 
# two types of languages "java and angular"

name: CICD
description: 'continuos integration'
# setting input
inputs:
  # project name, eguals to product name example ancillaries
  project-name:
    description: 'project global name'
    required: true
  # ejecute integration test, soap request or rest
  testIntegration:
    description: 'active test integration'
    required: false
    default: false
  testIntegration-path:
    description: 'path'
    required: false
    default: '${{ github.workspace }}'
  # control scan code
  scancode:
    description: 'scan code'
    required: true
    default: false
  # control quality code with sonar
  sonarqube-host:
    description: 'sonar host parameter'
    required: false
  sonarqube-user:
    description: 'sonar user parameter'
    required: false
  sonarqube-token:
    description: 'sonar token parameter'
    required: false
  sonarqube-client-version:
    description: 'sonar-scanner client version parameter v.r.f.build'
    required: false
  # control vulnerability code with kiuwan
  kiuwan-host:
    description: 'kiuwan host parameter'
    required: false
  kiuwan-user:
    description: 'kiuwan user parameter'
    required: false
  kiuwan-token:
    description: 'kiuwan token parameter'
    required: false
   # control vulnerability code with kiuwan
  repository-host:
    description: 'repository artifact host parameter'
    required: true
  repository-user:
    description: 'repository artifact user parameter'
    required: true
  repository-token:
    description: 'repository artifact token parameter'
    required: true  
  # terraform module
  terraform-version:
    description: 'terraform module'
    required: false
  terraform-module-path:
    description: 'path modules terraform'
    required: false

on: [pull_request]
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
      - develop
jobs:
  build:
    name: build
    runs-on: [self-hosted]
    # setting output step build to use other jobs steps
    outputs:
      package-groupid-name:
        description: "Package build generator Group Id"
        value: ${{ steps.package-generator-name.outputs.package-group }}
      package-artifactid-name:
        description: "Package build generator artifact Id"
        value: ${{ steps.package-generator-name.outputs.package-artifact }}
      package-version-name:
        description: "Package build generator version"
        value: ${{ steps.package-generator-name.outputs.package-version }} 
      package-type-name:
        description: "package type example: jar, war, zip"
        value: ${{ steps.package-generator-name.outputs.package-type-id }}
      package-repository:
        description: "package repository path"
        value: ${{ steps.registry-repository.outputs.registry-repository-id }}    
    env:
      SCRIPT: ${{ github.workspace }}/.github/action/utils/
      LANGUAGE:
    steps:
      # Nota: 
      # Remplace action's with custom shell script to future
      # for segurity - location in (../utils/)
      # Step 1 
      - name: checkout
        uses: actions/checkout@v2
      # Step 2 - Reemplace with install process jdk and configure path environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Step 3 - Reemplace with install process node.js
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Step 4
      - name: Building Artifact
        id: package-generator-name
        shell: bash
        run: |
        ${{ env.SCRIPT }}/build.sh ${{ github.workspace }} ${{ env.LANGUAGE }} ${{ github.ref }}
    steps:
      # implement sonar
      # Step 1
      - name: Scan
        shell: bash
        env:
          GROUP:  ${{ jobs.build.outputs.package-groupid-name }}   # get package name generate from step build
          ARTIFACT:  ${{ jobs.build.outputs.package-artifactid-name }}   # get package name generate from step build
          VERSION:  ${{ jobs.build.outputs.package-version-name }}   # get package name generate from step build
          PACKAGE: ${{ jobs.build.outputs.package-type-name }} # get package type extention from step build
          SONAR_URL: inputs.sonarqube-host
          SONAR_USER: inputs.sonarqube-user
          SONAR_SECRET: inputs.sonarqube-token
          SONAR_CLI: inputs.sonarqube-client-version
        run: |
        ${{ env.SCRIPT }}/sonar-scanner.sh ${{ env.SONAR_URL }} ${{ env.SONAR_USER }} ${{ env.SONAR_SECRET }} ${{ env.SONAR_CLI }} ${{ env.LANGUAGE }} ${{ github.ref }} ${{ github.GROUP }} ${{ github.ARTIFACT }} ${{ github.VERSION }} 
    steps:
      # deploy artifact to registry repository
      - name: Registy artifact
        id: registry-repository
        shell: bash
        env:
          GROUP:  ${{ jobs.build.outputs.package-groupid-name }}   # get package name generate from step build
          ARTIFACT:  ${{ jobs.build.outputs.package-artifactid-name }}   # get package name generate from step build
          VERSION:  ${{ jobs.build.outputs.package-version-name }}   # get package name generate from step build
          PACKAGE: ${{ jobs.build.outputs.package-type-name }} # get package type extention from step build
          # DNS hasn't content http:// or https://
          REPOSITORY_DNS: inputs.repository-host
          REPOSITORY_USER: inputs.repository-user
          REPOSITORY_SECRET: inputs.repository-token
        run: |
        # path in script repository nexus defaults is /repository/snapshots/ and /repository/releases/ for java and npm-private for angular node package
        ${{ env.SCRIPT }}/nexus-registry.sh ${{ env.REPOSITORY_DNS }} ${{ env.REPOSITORY_USER }} ${{ env.REPOSITORY_SECRET }} ${{ env.LANGUAGE }} ${{ github.ref }} ${{GROUP}} ${{ARTIFACT}} ${{VERSION}}
  image:
    name: image
    runs-on: [self-hosted]
    outputs:
      image-number-id:
        description: "image number id"
        value: ${{ steps.image-generator.outputs.image-id }}
    env:
      SCRIPT: ${{ github.workspace }}/.github/action/utils/
      USER:    
      DEPARTAMENT:
      LANGUAGE:
      PROJECT:  ${{ inputs.project-name }}   # get input name, this name use in dns site and global value. project = product business
      GROUP:  ${{ jobs.build.outputs.package-groupid-name }}   # get package name generate from step build
      ARTIFACT:  ${{ jobs.build.outputs.package-artifactid-name }}   # get package name generate fromstep build
      VERSION:  ${{ jobs.build.outputs.package-version-name }}   # get package name generate from step build
      PACKAGE: ${{ jobs.build.outputs.package-type-name }} # get package type extention from step build
      REPOSITORY_PATH:  ${{ jobs.build.outputs.package-repository }}   # get path repository package generate font step build
      REPOSITORY_HOST: inputs.repository-host
      REPOSITORY_USER: inputs.repository-user    # change user to read, now use write
      REPOSITORY_SECRET: inputs.repository-token   # change token to read, now use write
    steps:
      # build image
      # Step 1
      - name: build image
        id: image-generator
        shell: bash
        run: |
        ${{ env.SCRIPT }}/build-image.sh ${{ env.USER }} ${{ env.DEPARTAMENT }} ${{ env.LANGUAGE }} ${{ env.GROUP }} ${{ env.ARTIFACT }} ${{ env.VERSION }} ${{ env.PACKAGE}} ${{ env.REPOSITORY_HOST }} ${{ env.REPOSITORY_USER }} ${{ env.REPOSITORY_SECRET }} ${{ env.REPOSITORY_PATH }} ${{ env.PROJECT }} ${{ github.workspace }}
  deploy:
    name: deploy
    runs-on: [self-hosted]
    env:
      SCRIPT: ${{ github.workspace }}/.github/action/utils/
      TEST: inputs.testIntegration
      LANGUAGE: 
      AMI_ID: ${{ jobs.image.outputs.image-number-id }}
      PROJECT:  ${{ inputs.project-name }}   # get input name, this name use in dns site and global value. project = product business
      AMI_VERSION:  ${{ jobs.build.outputs.package-version-name }}   # get package version generate from step build
    steps:
      # instance software.
      # Step 1
      - name: Deploy
        shell: bash
        run: |
        ${{ env.SCRIPT }}/terraform-deploy.sh ${{ env.PROJECT }} ${{ env.AMI_VERSION }} ${{ env.AMI_ID }} 
      # Step 2
      - name: Health Check
        shell: bash
        run: |
        ${{ env.SCRIPT }}/health-checking.sh ${{ env.aws_alb_target_group_arn }}
      # Step 3
      - name: Integration tests
        shell: bash
        run: |
        ${{ env.SCRIPT }}/get-tools.sh ${{ env.TEST }}
        ${{ env.SCRIPT }}/integration-tests.sh ${{ env.TEST }}